#!usr/bin/python

import re
import numpy as np

chromosomes = ['1','2','3','4','5','6','7','8','9','10','11', '12', '13', '14', '15', 
				'16', '17', '18', '19', '20', '21', '22', 'X', 'Y', 'M']
				
for chromsome in chromosomes:
  filename = 'new_chr_files/chr'+chromsome+'.txt'
    coverage = 0
    cur_pos = 0
    
    for line in coverage_file:
      line = line.replace('\n','').split('\t')
      
      if line[1] != cur_pos
        cur_pos = line[1]
        coverage = 1
        chroms = np.zeros(25)
        chroms[int(line[2]) +=1
        lines = [line]
        
      
